In [11]:
### ЗАВДАННЯ 1.1
import numpy as np
arr1_1 = np.array([[1.1, 2.2, 3.3, 4.4],
                   [5.5, 6.6, 7.7, 8.8],
                   [9.9, 10.1, 11.2, 12.3]])
print(arr1_1)
print(arr1_1.dtype)
print(arr1_1.shape)
print(arr1_1.ndim)
print(arr1_1.size)
print(len(arr1_1))
print(arr1_1.itemsize)
print(arr1_1.nbytes)

[[ 1.1  2.2  3.3  4.4]
 [ 5.5  6.6  7.7  8.8]
 [ 9.9 10.1 11.2 12.3]]
float64
(3, 4)
2
12
3
8
96


In [12]:
### ЗАВДАННЯ 1.2
arr1_2 = np.array(['apple', 'banana', 'cherry', 'date', 'elderberry'])
print(arr1_2)

['apple' 'banana' 'cherry' 'date' 'elderberry']


In [13]:
### ЗАВДАННЯ 1.3
arr1_3 = np.ones((3, 4))
print(arr1_3)
print(arr1_3.dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64


In [14]:
### ЗАВДАННЯ 2.1
arr2_1 = np.full((3,1,3), False, dtype=bool)
print(arr2_1)

[[[False False False]]

 [[False False False]]

 [[False False False]]]


In [15]:
### ЗАВДАННЯ 2.2
arr2_2 = arr2_1.reshape((3, 3)).astype('int')
print(arr2_2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [29]:
### ЗАВДАННЯ 2.3
arr2_3 = np.arange(10, 22, 2).reshape((2, 3))
print(arr2_3)

[[10 12 14]
 [16 18 20]]


In [31]:
### ЗАВДАННЯ 3.1
arr3_1 = np.random.normal(loc=55, scale=15, size=(4, 5))
arr3_1 = np.clip(arr3_1, 10, 100)
print(arr3_1)

[[65.55312095 25.02341624 60.92841835 53.85592785 81.17539477]
 [42.42791364 40.74062064 62.49002305 79.53511016 76.37980655]
 [60.86626342 67.87001567 52.20718867 62.55260267 47.25878085]
 [53.22018208 33.1631645  45.67575003 63.83454384 66.0406485 ]]


In [34]:
### ЗАВДАННЯ 3.2
el3_2 = arr3_1[1, 2]
print(el3_2)

62.49002304792259


In [35]:
### ЗАВДАННЯ 3.3
vect3_3 = arr3_1[1, :]
print(vect3_3)


[42.42791364 40.74062064 62.49002305 79.53511016 76.37980655]


In [36]:
### ЗАВДАННЯ 3.4
vect3_4 = arr3_1[:, 2]
print(vect3_4)

[60.92841835 62.49002305 52.20718867 45.67575003]


In [37]:
### ЗАВДАННЯ 3.5
mat3_5 = arr3_1[1:3, 1:3]
print(mat3_5)

[[40.74062064 62.49002305]
 [67.87001567 52.20718867]]


In [71]:
# ЗАВДАННЯ 4.1
mat4_1 = np.random.randint(100, 200, size=(6, 6))
print(mat4_1)

[[188 170 126 136 169 190]
 [113 109 119 155 177 185]
 [123 172 146 103 176 106]
 [125 110 111 129 103 195]
 [132 183 124 141 160 192]
 [119 174 190 155 142 138]]


In [72]:
# ЗАВДАННЯ 4.2
diag4_2 = np.diag(mat4_1)
print(diag4_2)

[188 109 146 129 160 138]


In [73]:
# ЗАВДАННЯ 4.3
trans4_3 = mat4_1.T
print(trans4_3)

[[188 113 123 125 132 119]
 [170 109 172 110 183 174]
 [126 119 146 111 124 190]
 [136 155 103 129 141 155]
 [169 177 176 103 160 142]
 [190 185 106 195 192 138]]


In [74]:
# ЗАВДАННЯ 4.4
inv4_4 = np.linalg.inv(mat4_1)
print(mat4_1)

[[188 170 126 136 169 190]
 [113 109 119 155 177 185]
 [123 172 146 103 176 106]
 [125 110 111 129 103 195]
 [132 183 124 141 160 192]
 [119 174 190 155 142 138]]


In [101]:
# ЗАВДАННЯ 5.1
mat5_1 = np.random.randint(1, 10, (3,4))
sum_mat5_1 = np.sum(mat5_1, axis=1)
print(mat5_1)
print(sum_mat5_1)

[[2 6 3 9]
 [9 5 6 4]
 [2 1 3 7]]
[20 24 13]


In [102]:
# ЗАВДАННЯ 5.2
min_mat5_1 = np.min(sum_mat5_1)
print(min_mat5_1)


13


In [110]:
# ЗАВДАННЯ 5.3
mat5_3 = mat5_1 + 100
print(mat5_3)

[[102 106 103 109]
 [109 105 106 104]
 [102 101 103 107]]
