# Лабораторна робота "Операції над масивами NumPy"

__Метою__ лабораторної роботи є набуття практичних навичок та закріплення теоретичних знань по обробці великих однорідних наборів даних які розташовані у вигляді масивів бібліотеки __NumPy__.

Виконати послідовно завдання в секціях, попередню засвоївши наведені приклади
В завданнях продовжити написання коду замість `...`. 

__Імена змінних в завданнях змінювати не можна!__

### Предвстановлення

In [1]:
# Імпортувати бібліотеку numpy з аліасом np
import numpy as np

In [2]:
# Вивід таблиці відповідності кодів типів даних в NumPy
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

## 1. Створення та інспектування _np-массивів_

### ПРИКЛАДИ

In [3]:
# Створити 1-вимірний масив з 5 цілочисельних елементів 
arr = np.array([23, 42, 13, 7, 0])

In [4]:
# Інспектування массива
np.info(arr)

class:  ndarray
shape:  (5,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x23fd69a4cc0
byteorder:  little
byteswap:  False
type: int32


In [5]:
# створити 2-мірний масив з цілим типом даних у 2-х байтовому форматі
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
# створити масив із  значень в інтервалі 0 - 20 з кроком 2
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [7]:
# створити масив із 20 рівномірно розміщених значень в інтервалі 0 - 10 
# np.linspace(start, stop, num_of_elements) 
arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [8]:
# створити масив 3х3 випадкових значень 
arr = np.random.rand(3, 3)
print(arr)

[[0.53103082 0.88821659 0.97452026]
 [0.9790294  0.38979543 0.65011207]
 [0.5879932  0.56033064 0.25229649]]


In [9]:
# створення нульвих, одиничних та заповнених масивів
zeros = np.zeros((2,3), dtype='i4')
print(zeros)
ones = np.ones((2,3))
print(ones)
filled = np.full((2,3), 123)
print(filled)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[123 123 123]
 [123 123 123]]


In [10]:
print(arr, end="\n...\n")
# інспектування типу массиву `dtype`
print(arr.dtype)
# інспектування розмірності массиву `shape`
print(arr.shape)
# інспектування довжини масиву `len`
print(len(arr))
# інспектування кількості вимірів масиву `ndim`
print(arr.ndim)
# інспектування кількості елементів в масиві `size`
print(arr.size)
# інспектування коількості байтів на елемент `itemsize`
print(arr.itemsize)
# інспектування кількості пам'яти під масив `nbytes`
print(arr.nbytes)

[[0.53103082 0.88821659 0.97452026]
 [0.9790294  0.38979543 0.65011207]
 [0.5879932  0.56033064 0.25229649]]
...
float64
(3, 3)
3
2
9
8
72


In [11]:
arr.__sizeof__()

192

### ЗАВДАННЯ 1

In [12]:
### ЗАВДАННЯ 1.1: створити та проінспектувати масив 3х4 з ім'ям arr1_1, який містить числа з плавоючою точкою 
arr1_1 = np.array([100, 15, 24, 31.5, 94, 85, 76, 64.2, 91.7, 45.9, 38, 72]).reshape(3, 4)

print(arr1_1)

print(f"\nТип масиву (dtype):\t\t\t{arr1_1.dtype}")
print(f"Розмірність масиву (shape):\t\t{arr1_1.shape}")
print(f"Кількість вимірів масиву `ndim):\t{arr1_1.ndim}")
print(f"Кількість елементів в масиві (size):\t{arr1_1.size}")
print(f"Довжина масиву (len):\t\t\t{len(arr1_1)}")
print(f"Кількість байтів на елемент (itemsize):\t{arr1_1.itemsize}")
print(f"Кількість пам'яти під масив (nbytes):\t{arr1_1.nbytes}")

[[100.   15.   24.   31.5]
 [ 94.   85.   76.   64.2]
 [ 91.7  45.9  38.   72. ]]

Тип масиву (dtype):			float64
Розмірність масиву (shape):		(3, 4)
Кількість вимірів масиву `ndim):	2
Кількість елементів в масиві (size):	12
Довжина масиву (len):			3
Кількість байтів на елемент (itemsize):	8
Кількість пам'яти під масив (nbytes):	96


In [66]:
### ЗАВДАННЯ 1.2: створити одномірний масив з 5 строкових елементів
arr1_2 = np.array(['apple', 'banana', 'cherry', 'date', 'elderberry'])
print(arr1_2)

['apple' 'banana' 'cherry' 'date' 'elderberry']


In [71]:
### ЗАВДАННЯ 1.3: створити одиничний масив 3х4 чисел з плаваючою точкою
arr1_3 = np.ones((3, 4), dtype=float)
print(arr1_3)
print(arr.dtype)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64


## 2. Перетворення форми та типу массивів

### ПРИКЛАДИ

In [72]:
# створити 2-мірний float-масив (2х5) з лінійного int-списка 
spisok = list(range(0,10))
arr = np.array(spisok)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [73]:
#преретворити форму масива `reshape` 
arr = arr.reshape((2,5))
print(arr)
print(arr.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32


In [74]:
# -- 3 перетворити тип масива `astype`
arr = arr.astype('float64')
print(arr)
print(arr.dtype)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
float64


In [75]:
# 'вирівняти' 2-мірний масив
arr = arr.flatten()
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### ЗАВДАННЯ 2

In [76]:
### ЗАВДАННЯ 2.1: створити 3-мірний масив (3х1х3) логічного 'False'
arr2_1 = np.array([False]*9)
arr2_1 = arr2_1.reshape(3, 1, 3)
print(arr2_1)

[[[False False False]]

 [[False False False]]

 [[False False False]]]


In [77]:
### ЗАВДАННЯ 2.2: перетворити масив arr2_1 в 2-мірний масив (3х3) типу int
arr2_2 = arr2_1.reshape(3, 3)
arr2_2 = arr2_2.astype('int')
print(arr2_2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [78]:
### ЗАВДАННЯ 2.3: створити  2-мірний масив парних чисел в інтервалі 10-21
arr2_3 = np.arange(10, 21, 2)
arr2_3 = arr2_3.reshape(3, -1)
print(arr2_3)

[[10 12]
 [14 16]
 [18 20]]


## 3. Доступ до  елементів масива

### ПРИКЛАДИ

In [79]:
arr = np.array([10, 6, 7, 21, 44]) 
print(arr)

# 1-й елемент 
print(arr[0])
# 3-й елемент
print(arr[2])
# останній елемент
print(arr[-1])

[10  6  7 21 44]
10
7
44


In [80]:
# створити 2-мірний масив з цілих чисел з інтервалу 10-50
arr = np.random.randint(10, 50, (4,4))
print(arr)

[[23 42 47 15]
 [14 26 32 37]
 [39 22 38 48]
 [26 12 36 22]]


In [81]:
# отримати значення останнього елемента в 2 рядку
el = arr[1, -1]
print(el)

37


In [82]:
# отримати значення останнього рядка
vect = arr[-1]
print(vect)

[26 12 36 22]


In [83]:
# отримати `зріз` з 1 по 2 рядок
mat = arr[0:2]
print(mat)

[[23 42 47 15]
 [14 26 32 37]]


In [84]:
# вилучити 2 та 3 стовбчики `arr`
mat = arr[0:4, 1:3]
print(mat)

[[42 47]
 [26 32]
 [22 38]
 [12 36]]


In [85]:
# вилучити непарні рядки `arr`
mat = arr[0:4:2]
print(mat)

[[23 42 47 15]
 [39 22 38 48]]


In [86]:
# фільтрувати елементи масива за умовою
els = arr[arr > 20]
print(els)

[23 42 47 26 32 37 39 22 38 48 26 36 22]


### ЗАВДАННЯ 3

In [87]:
### ЗАВДАННЯ 3.1: створити масив 4х5 нормально розподілений випадкових чисел 3 інтервалу [10 - 100]
arr3_1 = np.linspace(10, 100, 20).reshape(4, 5)
print(arr3_1)

[[ 10.          14.73684211  19.47368421  24.21052632  28.94736842]
 [ 33.68421053  38.42105263  43.15789474  47.89473684  52.63157895]
 [ 57.36842105  62.10526316  66.84210526  71.57894737  76.31578947]
 [ 81.05263158  85.78947368  90.52631579  95.26315789 100.        ]]


In [88]:
### ЗАВДАННЯ 3.2:  вивести 3-елемент в 2-му рядку
el3_2 = arr3_1[1, 2]
print(el3_2)

43.1578947368421


In [89]:
### ЗАВДАННЯ 3.3:  вивести 2-й рядок масива `arr3_1`
vect3_3 = arr3_1[1]
print(vect3_3)

[33.68421053 38.42105263 43.15789474 47.89473684 52.63157895]


In [90]:
### ЗАВДАННЯ 3.4:  вивести 3 колонку масива `arr3_1`
vect3_4 = arr3_1[:,2]
print(vect3_4)

[19.47368421 43.15789474 66.84210526 90.52631579]


In [91]:
### ЗАВДАННЯ 3.5: вивести матрицю  з 2 та 3 рядка та 2 та 3 колонки масива `arr3_1`
mat3_5 = arr3_1[1:3, 1:3]
print(mat3_5)

[[38.42105263 43.15789474]
 [62.10526316 66.84210526]]


## 4. Матричні компоненти масива

### ПРИКЛАДИ

In [92]:
# створити одиничну матрицю розміру 3х3
mat = np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [93]:
# створити матрицю із заданою диагоналлю
mat = np.diag([1,2,3,4,5])
print(mat)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [94]:
# вилучити головну діагональ матриці `diag`
mat = np.random.rand(5,5)
print(mat, end="\n...\n")
print(np.diag(mat))

[[0.26689985 0.65612798 0.89025316 0.09641199 0.79185442]
 [0.74517832 0.8531767  0.84684755 0.97033083 0.42048314]
 [0.9794313  0.29973255 0.40262313 0.96280095 0.63270911]
 [0.0793818  0.46067476 0.82213337 0.82410662 0.83912511]
 [0.32321799 0.22693978 0.18306143 0.99293523 0.63510539]]
...
[0.26689985 0.8531767  0.40262313 0.82410662 0.63510539]


In [95]:
# транспонувати матрицю `mat` (https://ru.wikipedia.org/wiki/Транспонированная_матрица)
mT = np.transpose(mat)
print(mT)

[[0.26689985 0.74517832 0.9794313  0.0793818  0.32321799]
 [0.65612798 0.8531767  0.29973255 0.46067476 0.22693978]
 [0.89025316 0.84684755 0.40262313 0.82213337 0.18306143]
 [0.09641199 0.97033083 0.96280095 0.82410662 0.99293523]
 [0.79185442 0.42048314 0.63270911 0.83912511 0.63510539]]


In [96]:
# отримати детермінант матриці `det` (https://ru.wikipedia.org/wiki/Определитель)
print(np.linalg.det(mat))

-0.1295286001657499


In [97]:
# отримати зворотню матриці `det` (https://ru.wikipedia.org/wiki/Обратная_матрица)
invM = np.linalg.inv(mat)
print(invM)

[[ 1.93579228e-01 -1.06660685e-01  1.33341300e+00 -5.93591472e-01
  -7.14846068e-01]
 [ 1.63657732e+00  1.43174598e+00 -2.29215562e+00 -2.78755583e+00
   2.97811961e+00]
 [-1.25593845e+00 -1.10459381e-01  1.30870362e+00  2.79760497e+00
  -3.36102104e+00]
 [-1.09238666e+00  4.16688058e-01 -1.49327888e-01  7.81870221e-01
   2.01848524e-01]
 [ 1.38655777e+00 -1.07693758e+00 -3.30973279e-03 -7.30608381e-01
   1.52738136e+00]]


### ЗАВАДАННЯ 4

In [98]:
# ЗАВДАННЯ 4.1: створити квадратну матрицю з 36 рівномірно розподілених цілих 
# елементів з інтервалу 100 - 200
mat4_1 = np.round(np.linspace(100, 200, 36), 3).reshape(6,6)
print(mat4_1)

[[100.    102.857 105.714 108.571 111.429 114.286]
 [117.143 120.    122.857 125.714 128.571 131.429]
 [134.286 137.143 140.    142.857 145.714 148.571]
 [151.429 154.286 157.143 160.    162.857 165.714]
 [168.571 171.429 174.286 177.143 180.    182.857]
 [185.714 188.571 191.429 194.286 197.143 200.   ]]


In [123]:
# ЗАВДАННЯ 4.2: вивести головну діагональ матниці `mat4_1`
diag4_2 = np.diag(mat4_1)
print(diag4_2)

[100. 120. 140. 160. 180. 200.]


In [124]:
# ЗАВДАННЯ 4.3: транспонувати матрицю 'mat4_1'
trans4_3 = mat4_1.T
print(trans4_3)

[[100.    117.143 134.286 151.429 168.571 185.714]
 [102.857 120.    137.143 154.286 171.429 188.571]
 [105.714 122.857 140.    157.143 174.286 191.429]
 [108.571 125.714 142.857 160.    177.143 194.286]
 [111.429 128.571 145.714 162.857 180.    197.143]
 [114.286 131.429 148.571 165.714 182.857 200.   ]]


In [125]:
# ЗАВДАННЯ 4.4: вирахувати зворотню до 'mat4_1' матрицю 
inv4_4 = np.linalg.inv(mat4_1)
print(inv4_4)

[[ 7.77179326e-10  4.18219470e-13 -1.00000000e+03  2.00000000e+03
  -1.00000000e+03 -3.02124972e-11]
 [ 7.77343136e-10  9.31407193e-14 -1.00000000e+03  1.00000000e+03
   1.00000000e+03 -1.00000000e+03]
 [ 1.00000000e+03  1.00000000e+03 -3.26680281e+00 -4.99708321e+03
   1.00000000e+03  2.00000000e+03]
 [-2.00000000e+03 -1.00000000e+03  5.00320847e+03 -2.85845248e+00
  -1.00000000e+03 -1.00000000e+03]
 [ 1.00000000e+03 -1.00000000e+03 -1.00000000e+03  1.00000000e+03
   1.46387890e-10 -3.68454908e-10]
 [ 1.55423822e-09  1.00000000e+03 -2.00000000e+03  1.00000000e+03
   2.97730150e-10  3.68539250e-10]]


## 5. Операції над масивами

### ПРИКЛАДИ

In [156]:
# задати вектор з 10 елементів
vect = np.array([1, 3, 2, -3, 5, 0])

In [157]:
# вирахувати суму елеметнів
s = np.sum(vect)

# знайти мінімальний ел-т
m = np.min(vect)

# відсортувати вектор по зростанню
vs = np.sort(vect)

# знайти середнє значення
mid = np.average(vect)

print(s, m, vs, mid)

8 -3 [-3  0  1  2  3  5] 1.3333333333333333


In [158]:
# матриця 3х3 сконструйована різними методами
mat = np.array([np.arange(1,4), [-2, 4, 6], np.full(3,77)])
print(mat)

[[ 1  2  3]
 [-2  4  6]
 [77 77 77]]


In [159]:
# сума по колонкам `axis=0`
s = np.sum(mat, axis=0)
print(s)

[76 83 86]


In [160]:
# мінімум по рядкам
m = np.min(mat, axis=1)
print(m)

[ 1 -2 77]


In [161]:
# збільшити ел-ти масива вдвічі
v2 = mat * 2
print(v2)

[[  2   4   6]
 [ -4   8  12]
 [154 154 154]]


In [162]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(M, N, sep="\n")

[[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [163]:
# перемножити елементи матриць M, N
K = M * N
print(K)
# або ->
K = np.multiply(N, M)
print(K)

[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]
[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]


In [164]:
# поелементний поділ
K = N / M
print(K)

[[ 1.          0.5         0.33333333]
 [ 0.5        -0.66666667  0.33333333]
 [ 0.42857143  0.375              inf]]


C:\Users\w\AppData\Local\Temp\ipykernel_20212\3347190385.py:2: RuntimeWarning: divide by zero encountered in true_divide
  K = N / M


In [165]:
# скалярне множення матриць (https://ru.wikipedia.org/wiki/Умножение_матриц)
prod = np.dot(N, M)
print(prod)

[[12  7  9]
 [24 14 18]
 [36 21 27]]


In [166]:
# возвести матрицю `prod` в ступінь 3
pmat = np.linalg.matrix_power(prod, 3)
print(pmat)

[[ 33708  19663  25281]
 [ 67416  39326  50562]
 [101124  58989  75843]]


In [167]:
# додати елементи до 1-вимірного масива
mat = np.array([1,2,3])
mat = np.append(mat, [5,6,7,8])
print(mat)

[1 2 3 5 6 7 8]


In [168]:
# вставити елемент `4` в масив після 3-го елемента
mat = np.insert(mat, 3, 4)
print(mat)

[1 2 3 4 5 6 7 8]


In [169]:
# видалити елемент з індексом 6
mat = np.delete(mat, 6)
print(mat)

[1 2 3 4 5 6 8]


In [170]:
#  копіювання та присвоювання масивів
M = np.random.randint(1, 10, 5 )
print(M)

# присвоїти масив `M` в `N`
N = M
print(N)
print(id(M), id(N))

# копіювати масив `M` в `K`
K = np.copy(M)
print(K)
print(id(M), id(K))

[2 3 6 3 9]
[2 3 6 3 9]
2473248473520 2473248473520
[2 3 6 3 9]
2473248473520 2473202681968


In [171]:
# конкатенація масивів по рядкам
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)
# по колонкам `axis = 1`
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ЗАВДАННЯ 5

In [150]:
# ЗАВДАННЯ 5.1: просумувати по рядкам масив випадкових чисел розмірностю 3х4
mat5_1 = np.random.randint(10, size=(4, 3))
sum_mat5_1 = np.sum(mat5_1, axis=1)

print(mat5_1, '\n...\n')
print(sum_mat5_1)

[[5 5 4]
 [8 5 4]
 [1 1 0]
 [5 5 3]] 
...

[14 17  2 13]


In [151]:
# ЗАВДАННЯ 5.2: знайти мінімальний елемент матриці `sum_mat5_1`
min_mat5_1 = min(sum_mat5_1)
print(min_mat5_1)

2


In [152]:
# ЗАВДАННЯ 5.3: створити масив додавши до елементів `mat5_1`  число 100
mat5_3 = mat5_1 + 100
print(mat5_3)

[[105 105 104]
 [108 105 104]
 [101 101 100]
 [105 105 103]]


In [153]:
# ЗАВДАННЯ 5.4: помножити матрицю `mat5_1` на головну діагональ матриці `mat5_3`
mat5_4 = np.array([np.dot(mat5_1, np.diag(mat5_3))])
print(mat5_4)

[[1450 1765  210 1350]]


In [154]:
# ЗАВДАННЯ 5.5: додати справа до матриці `mat5_3` матрицю `mat5_4` 
# вивести ранг отриманої матриці
mat5_5 = np.concatenate((mat5_3, mat5_4.T), axis=1)

print(mat5_5)
print("Mat5_5 rank: ", np.linalg.matrix_rank(mat5_5))

[[ 105  105  104 1450]
 [ 108  105  104 1765]
 [ 101  101  100  210]
 [ 105  105  103 1350]]
Mat5_5 rank:  4
